# Generated by Django 4.1.4 on 2023-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='points',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='points',
            name='phone_number',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='points',
            name='street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='points',
            name='town_or_city',
            field=models.CharField(default='', max_length=80),
        ),
    ]
