# Generated by Django 3.0.1 on 2023-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20230505_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
