# Generated by Django 4.1.4 on 2023-01-19 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0002_remove_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_id', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='profiles.userprofile')),
                ('product', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
    ]
