# Generated by Django 4.1.4 on 2023-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_qnt',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
