# Generated by Django 3.0.1 on 2023-05-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='copies',
            new_name='product_size',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='folder_sizes',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lunchbox',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='pencil_case',
        ),
    ]
