# Generated by Django 4.1.4 on 2023-03-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_user_points',
        ),
    ]
