# Generated by Django 4.1.4 on 2023-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_phone_number_alter_order_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
