# Generated by Django 4.1.4 on 2023-01-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_prodile',
            new_name='user_profile',
        ),
    ]
