# Generated by Django 4.1.4 on 2023-03-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, default=0, max_length=254, null=True),
        ),
    ]
