# Generated by Django 4.1.4 on 2023-01-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
